### ISSUE TITLE
Required java implementation or library

### ISSUE THREAD

**Issue by 969rishi** [bidrohi/asymmetrical-gallery-example#1]
I want to use this approach in my application but this is made in kotlin, I can't able to use this in my java application. Please can you create same project in java or just give us the library so that anyone can use this in their application. And please provide option for paginated data.

Please reply

**Comment by bidrohi** [comment]
There is nothing Kotlin specific about the implementation. Just translate the solution in Java. The implementation is explained here. https://medium.com/android-news/asymmetrical-grid-layout-using-recyclerview-5ed44899d7b5
